# This file is automatically generated by `./configs/reproduce/change_detection/generators/gen_fc_siam_oscd.py`.
# Please do not attempt to modify manually.
import torch
import data
import models
import criteria
import metrics
import optimizers
import runners


collate_fn_cfg = {
    'class': data.collators.BaseCollator,
    'args': {
        'collators': {
            'meta_info': {
                'date_1': list,
                'date_2': list,
            },
        },
    },
}

class_dist = torch.Tensor(data.datasets.OSCDDataset.CLASS_DIST['train']).to(torch.float32)
num_classes = data.datasets.OSCDDataset.NUM_CLASSES
class_weights = num_classes * (1/class_dist) / torch.sum(1/class_dist)

config = {
    'runner': runners.SupervisedSingleTaskTrainer,
    'work_dir': None,
    'epochs': 100,
    # seeds
    'init_seed': None,
    'train_seeds': None,
    # dataset config
    'train_dataset': {
        'class': data.datasets.OSCDDataset,
        'args': {
            'data_root': "./data/datasets/soft_links/OSCD",
            'split': "train",
            'transforms_cfg': {
                'class': data.transforms.Compose,
                'args': {
                    'transforms': [
                        (
                            data.transforms.vision_2d.RandomCrop(size=(96, 96), interpolation=None),
                            [('inputs', 'img_1'), ('inputs', 'img_2'), ('labels', 'change_map')],
                        ),
                        (
                            data.transforms.vision_2d.RandomRotation(choices=[0, 90, 180, 270]),
                            [('inputs', 'img_1'), ('inputs', 'img_2'), ('labels', 'change_map')],
                        ),
                        (
                            data.transforms.Randomize(transform=data.transforms.vision_2d.Flip(axis=-1), p=0.5),
                            [('inputs', 'img_1'), ('inputs', 'img_2'), ('labels', 'change_map')],
                        ),
                        (
                            data.transforms.Randomize(transform=data.transforms.vision_2d.Flip(axis=-2), p=0.5),
                            [('inputs', 'img_1'), ('inputs', 'img_2'), ('labels', 'change_map')],
                        ),
                    ],
                },
            },
            'bands': None,
        },
    },
    'train_dataloader': {
        'class': data.dataloaders.BaseDataLoader,
        'args': {
            'batch_size': 32,
            'last_mode': "fill",
            'num_workers': 4,
            'collate_fn': collate_fn_cfg,
        },
    },
    'criterion': {
        'class': criteria.vision_2d.SemanticSegmentationCriterion,
        'args': {
            'class_weights': tuple(class_weights.tolist()),
        },
    },
    'val_dataset': {
        'class': data.datasets.OSCDDataset,
        'args': {
            'data_root': "./data/datasets/soft_links/OSCD",
            'split': "test",
            'transforms_cfg': {
                'class': data.transforms.Compose,
                'args': {
                    'transforms': [
                        (
                            data.transforms.vision_2d.RandomCrop(size=(96, 96), interpolation=None),
                            [('inputs', 'img_1'), ('inputs', 'img_2'), ('labels', 'change_map')],
                        ),
                    ],
                },
            },
            'bands': None,
        },
    },
    'val_dataloader': {
        'class': torch.utils.data.DataLoader,
        'args': {
            'batch_size': 1,
            'num_workers': 4,
            'collate_fn': collate_fn_cfg,
        },
    },
    'test_dataset': None,
    'test_dataloader': None,
    'metric': {
        'class': metrics.vision_2d.SemanticSegmentationMetric,
        'args': {
            'num_classes': 2,
        },
    },
    # model config
    'model': {
        'class': models.change_detection.FullyConvolutionalSiameseNetwork,
        'args': {
            'arch': None,
            'in_channels': None,
            'num_classes': 2,
        },
    },
    # optimizer config
    'optimizer': {
        'class': optimizers.SingleTaskOptimizer,
        'args': {
            'optimizer_config': {
                'class': torch.optim.Adam,
                'args': {
                    'weight_decay': 1.0e-04,
                },
            },
        },
    },
    # scheduler config
    'scheduler': {
        'class': torch.optim.lr_scheduler.PolynomialLR,
        'args': {
            'optimizer': None,
            'total_iters': None,
            'power': 0.95,
        },
    },
}

# dataset config
config['train_dataset']['args']['bands'] = "3ch"
config['val_dataset']['args']['bands'] = "3ch"

# model config
config['model']['args']['arch'] = "FC-Siam-conc"
config['model']['args']['in_channels'] = 3

# seeds
config['init_seed'] = 81565104
config['train_seeds'] = [27762215, 57945845, 64083695, 67828048, 91413715, 53381123, 41780800, 71051537, 46258869, 12660385, 11917690, 28194322, 58524994, 74652921, 97389511, 79859017, 77340092, 56144712, 97826565, 8109674, 43169794, 1583931, 14627731, 53809643, 95423711, 4458785, 3454073, 45272773, 69197155, 23816465, 10618412, 38792207, 77858580, 52838255, 56353741, 66567119, 77858225, 2902129, 642771, 53386270, 69903742, 51402692, 51603249, 63825042, 63188361, 57272108, 26516117, 84338144, 7331095, 48914447, 58806922, 76528962, 62456997, 89507576, 68929330, 45623711, 1087565, 46737600, 30306152, 14690958, 90725522, 56975094, 81083331, 79503596, 680708, 44056087, 65557691, 94457845, 37848019, 87968937, 97604957, 23939931, 82914112, 82099993, 17779339, 47007786, 31776497, 71655726, 97055774, 64686502, 50865812, 25447385, 33231069, 98554343, 17483362, 65361950, 16801986, 16676536, 93819958, 98104136, 65117942, 74009119, 98079322, 96675071, 8623646, 14095528, 126911, 75404197, 62668996, 56360900]
config['val_seeds'] = [31746026, 56814529, 85898853, 853624, 78126104, 80678578, 44181675, 30638943, 5421389, 31681585, 62547570, 94134318, 36809030, 15283451, 9797729, 33670875, 31477335, 45051145, 96626682, 27417051, 88299229, 3546719, 61315525, 83528228, 37486191, 75936368, 41045650, 54098031, 4008862, 12935627, 47221662, 8415296, 71001662, 93264886, 40363826, 75440024, 20242491, 55754947, 64940971, 83916056, 20284709, 85520534, 42862682, 6531975, 83038375, 41499482, 28337174, 37415065, 83068421, 35922420, 47023034, 73459977, 52601910, 63748736, 65278925, 362413, 15008159, 68158640, 59096238, 34918518, 22268127, 33965137, 17046322, 80153004, 49303273, 99930423, 96407975, 1970192, 40715871, 14657476, 95770025, 31495179, 44588157, 82720745, 54268621, 55317690, 71399440, 20290642, 45816161, 21131343, 54173228, 89339608, 82415582, 3954801, 99898301, 90833790, 80369198, 51870609, 42266571, 54626578, 82293477, 78222996, 97687776, 38617764, 75553363, 56766885, 44792982, 62684145, 67815175, 67529265]
config['test_seed'] = 15346639

# work dir
config['work_dir'] = "./logs/reproduce/change_detection/fc_siam_oscd/fc_siam_oscd_Siam_conc_3ch_run_2"
